### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by ppmarq1** [RWUBAKWANAYO/motorbike_booking_backend#10]
### NOTE: We are using 2 Kanban boards (Back-end and Front-end).

[Back-End Kanban Board](https://github.com/RWUBAKWANAYO/motorbike_booking_backend/projects/1)

[Front-End Kanban Board](https://github.com/RWUBAKWANAYO/motorbike_booking_frontend/projects/1)

 [Olivier](https://github.com/RWUBAKWANAYO)
 [Pedro](https://github.com/ppmarq1)
 [Joseph](https://github.com/Kwentsir)
 [Ghilain](https://github.com/Ghilain)
 [Paul](https://github.com/Epaltechs)

**Kanban Board Front-End**
![image](https://user-images.githubusercontent.com/93770917/193055241-9a5126b7-b46b-41be-a27a-9c7a23b6cd39.png)

**Kanban Board Back-End**
![image](https://user-images.githubusercontent.com/93770917/193055581-e1b6f7e1-71a0-4577-964c-2aba9fd8b7a7.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by rloterh** [comment]
Hi Pedro, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, using the project's Github issues link instead of a Pull Request. Kindly submit this activity creating a Pull Request with a descriptive title and description, and using the appropriate gitflow/Github flow, and then request for another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
